name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.17
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install
        run: bun install --frozen-lockfile

  test:
    name: Integration Tests
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.17
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install
        run: bun install --frozen-lockfile
      - name: Run all tests
        run: bun run test
